name: libgsf
run-name: Build libgsf
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    env:
      THIS_PROJECT_VERSION: ${{ github.ref_name }}
      THIS_PROJECT_SHA: ${{ github.sha }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build info
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server!"
          echo "🔎 This job builds Tic-tac-toe game."
          echo "This job is run from $(whoami)"
          echo "Current directory is $(pwd)"

      - name: Install packages
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt -y install autoconf autoconf-archive automake zlib1g-dev libglib2.0-dev libxml2-dev libbz2-dev autopoint libtool libbz2-dev make

      - name: Build ${{ github.ref }}
        run: |
          cmake -S . -B build
          cmake --build build

      #      - name: 'Upload Artifact build/tick'
      #        if: (!startsWith(github.ref, 'refs/tags/v'))
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: tick.zip
      #          path: build/tick
      #          compression-level: 0 # no compression

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          target_commitish: main
          prerelease: false
          files: |
            ci-release/*.zip

      - run: echo "🍏 This job's status is ${{ job.status }}."